### ISSUE TITLE
Sex, gender, and the profile page

### ISSUE THREAD

**Issue by edwardabraham** [TeHikuMedia/corpora#29]
The profile page has a field 'Sex' which is defined as 'Gender' through the tooltip. There is a lengthy discussion of this here: https://www.formulate.com.au/blog/sex-and-gender

One approach they recommend around gender is to have a multi-select box that allows for defining `Female`, `Male`, and then a text box for `Other` in which people can use whatever language they like to describe themselves. In our case this could be 'Wāhine', 'Tāne', and a te reo word for 'Other'. The field should be called gender though, rather than sex.

The profile page could be improved by explaining why this information is being collected (to ensure that we have representative speech across genders, ages, levels of proficiency, and areas), because these are all things that effect how people sound.

Also need to figure out the language that is used on the profile page. At the moment it is a mixture of English and Te Reo. Personally, I would like to see the project go full Te Reo, after all it is in the title :) Most of the actions are already indicated by icons, for those of us who are a little bit light in the Te Reo department!

**Comment by kmahelona** [comment]
Yup that’s really a matter of getting people to translate which I’m personally finding hard. What works? Go translate it yourself then someone will say it’s wrong and then you’ll get the proper translation ;). 

I use sex and gender interchangeably so that change can me made easily (even by you). As a Polynesian led project I think it’s improtant to include the additional roles recognized by our people rather than giving them the Other box.
