### ISSUE TITLE
Allow someone to give sentence level feedback.

### ISSUE THREAD

**Issue by edwardabraham** [TeHikuMedia/corpora#77]
I came across a sentence with the word "haikai", which I wanted to query (I think it should have been "hiakai"?), but there is currently no easy way to do this from within the app.

**Comment by kmahelona** [comment]
This should be QC'd on our end rather than making it a public facing review feature. Basically we have human data entry problems and we need to resolve that. @edwardabraham since you are a staff you should be able to search for that sentence in the back-end and then maybe just make an issue with the sentence in question here and I'll get a te reo speaker to review the sentence in question. Bonus points for posting the admin link.

**Comment by kmahelona** [comment]
Another note is whether "nonsense" is okay. Since we're training on sounds, shouldn't a non-word pronounced phonetically correct be okay?
